version: '3'
services:
  backend-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: 'mongo-container'
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=pennywiser
    ports:
      - '27017:27017'